const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const db = require("./backend/db/db");
const cardController = require("./backend/controller/cardControler");
const app = express();
app.use(express.json());
app.use(express.urlencoded());
app.use(cors());
app.get("/", cardController.getCards);
app.post("/", cardController.addCard);
app.delete("/", cardController.deleteCard);
app.listen(3000);
